// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SendToken$Type } from "./SendToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SendToken"]: SendToken$Type;
    ["contracts/SendToken.sol:SendToken"]: SendToken$Type;
  }

  interface ContractTypesMap {
    ["SendToken"]: GetContractReturnType<SendToken$Type["abi"]>;
    ["contracts/SendToken.sol:SendToken"]: GetContractReturnType<SendToken$Type["abi"]>;
  }
}
